name: test
url: https://github.com/alan-turing-institute/mapreader-plant-scivision.git
import: mapreader-plant-scivision
model: MapReader_model
args: None
prediction_fn:
    call: predict
    args:
        X: path2images
        slice_size: slice_size
        plot_output: plot_output
