name: test
url: https://github.com/alan-turing-institute/mapreader-plant-scivision.git
import: mapreader_model
model: MapReader_model
args:
    model_path: "./checkpoint_15.pkl"
prediction_fn:
    call: predict
    args:
        X: path2images
        
    kwargs: 
        slice_size: slice_size
