name: Continuous integration

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 
    - name: Install dependencies
      run: |
        $CONDA/bin/pip install scivision 
    - name: Test with pytest
      run: |
        $CONDA/bin/conda install pytest
        $CONDA/bin/pytest ./tests